services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistema_grc
    volumes:
      - grc_pg_data:/var/lib/postgresql/data

volumes:
  grc_pg_data:
